# Generated by Django 4.2.6 on 2023-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
