# Generated by Django 4.2.6 on 2023-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
