# Generated by Django 4.2.6 on 2024-01-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('out for shipping', 'out for shipping'), ('complete', 'Complete'), ('delivered', 'Delivered'), ('Cancel', 'cancel')], default='pending', max_length=150),
        ),
    ]
