# Generated by Django 4.2.6 on 2024-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_productoffer_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dis_price',
            field=models.FloatField(default=0),
        ),
    ]
