# Generated by Django 4.2.6 on 2024-02-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_remove_address_city_remove_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
