# Generated by Django 4.2.6 on 2024-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0027_alter_products_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
