# Generated by Django 4.2.6 on 2024-03-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0028_alter_products_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
