# Generated by Django 4.2.6 on 2024-03-14 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0029_rename_phonenumber_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.address'),
            preserve_default=False,
        ),
    ]
