# Generated by Django 4.2.6 on 2024-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0002_alter_customuser_email_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
