# Generated by Django 4.2.6 on 2024-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0003_customuser_my_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='my_wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
